/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'activeUsers' : bigint,
  'pendingApprovals' : bigint,
  'totalBlogPosts' : bigint,
  'totalListings' : bigint,
  'totalInquiries' : bigint,
}
export type BlogCategory = { 'news' : null } |
  { 'marketTrends' : null } |
  { 'buyingGuide' : null } |
  { 'rentalGuide' : null };
export interface BlogPost {
  'id' : BlogPostId,
  'metaDescription' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : BlogCategory,
}
export type BlogPostId = bigint;
export type ContentType = { 'blogPost' : null } |
  { 'property' : null };
export interface CreateBlogPostInput {
  'metaDescription' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : BlogCategory,
}
export interface CreateFlagInput {
  'contentId' : bigint,
  'contentType' : ContentType,
  'reason' : string,
}
export interface CreateInquiryInput {
  'inquiryType' : InquiryType,
  'propertyId' : PropertyId,
  'message' : string,
  'preferredTime' : [] | [string],
  'contactDetails' : string,
}
export interface CreateLocationInput {
  'latitude' : number,
  'name' : string,
  'slug' : string,
  'description' : string,
  'featuredImageUrl' : string,
  'longitude' : number,
  'parentId' : [] | [LocationId],
  'locationType' : LocationType,
}
export interface CreatePropertyInput {
  'latitude' : number,
  'title' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'city' : string,
  'neighborhood' : string,
  'sqft' : bigint,
  'description' : string,
  'amenities' : Array<string>,
  'longitude' : number,
  'address' : string,
  'bathrooms' : bigint,
  'price' : bigint,
  'photos' : Array<string>,
}
export type FlagAction = { 'remove' : null } |
  { 'dismiss' : null };
export type FlagId = bigint;
export type FlagStatus = { 'pending' : null } |
  { 'reviewed' : null } |
  { 'removed' : null };
export interface FlaggedContent {
  'id' : FlagId,
  'status' : FlagStatus,
  'contentId' : bigint,
  'contentType' : ContentType,
  'createdAt' : Timestamp,
  'reportedBy' : UserId,
  'reason' : string,
}
export interface Inquiry {
  'id' : InquiryId,
  'status' : InquiryStatus,
  'userId' : UserId,
  'inquiryType' : InquiryType,
  'createdAt' : Timestamp,
  'propertyId' : PropertyId,
  'message' : string,
  'preferredTime' : [] | [string],
  'contactDetails' : string,
}
export type InquiryId = bigint;
export type InquiryStatus = { 'closed' : null } |
  { 'responded' : null } |
  { 'pending' : null };
export type InquiryType = { 'requestCallback' : null } |
  { 'scheduleVisit' : null } |
  { 'contactAgent' : null };
export interface Location {
  'id' : LocationId,
  'latitude' : number,
  'name' : string,
  'slug' : string,
  'description' : string,
  'featuredImageUrl' : string,
  'longitude' : number,
  'parentId' : [] | [LocationId],
  'locationType' : LocationType,
}
export type LocationId = bigint;
export type LocationType = { 'city' : null } |
  { 'neighborhood' : null };
export interface Page {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Property>,
}
export interface Property {
  'id' : PropertyId,
  'status' : PropertyStatus,
  'latitude' : number,
  'title' : string,
  'verificationSource' : [] | [string],
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'city' : string,
  'neighborhood' : string,
  'createdAt' : Timestamp,
  'sqft' : bigint,
  'description' : string,
  'agentId' : UserId,
  'amenities' : Array<string>,
  'updatedAt' : Timestamp,
  'isFeatured' : boolean,
  'longitude' : number,
  'address' : string,
  'bathrooms' : bigint,
  'price' : bigint,
  'verifiedAt' : [] | [Timestamp],
  'photos' : Array<string>,
}
export type PropertyId = bigint;
export type PropertyStatus = { 'pending' : null } |
  { 'inactive' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type PropertyType = { 'studio' : null } |
  { 'commercial' : null } |
  { 'house' : null } |
  { 'villa' : null } |
  { 'apartment' : null };
export interface RegisterUserInput {
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'avatarUrl' : string,
  'phone' : string,
}
export interface SearchFilters {
  'propertyType' : [] | [PropertyType],
  'city' : [] | [string],
  'neighborhood' : [] | [string],
  'page' : bigint,
  'pageSize' : bigint,
  'amenities' : [] | [Array<string>],
  'minBedrooms' : [] | [bigint],
  'maxPrice' : [] | [bigint],
  'maxBedrooms' : [] | [bigint],
  'keyword' : [] | [string],
  'minPrice' : [] | [bigint],
  'minBathrooms' : [] | [bigint],
}
export type Timestamp = bigint;
export interface UpdateBlogPostInput {
  'metaDescription' : [] | [string],
  'title' : [] | [string],
  'content' : [] | [string],
  'isPublished' : [] | [boolean],
  'slug' : [] | [string],
  'tags' : [] | [Array<string>],
  'featuredImageUrl' : [] | [string],
  'excerpt' : [] | [string],
  'category' : [] | [BlogCategory],
}
export interface UpdateLocationInput {
  'latitude' : [] | [number],
  'name' : [] | [string],
  'slug' : [] | [string],
  'description' : [] | [string],
  'featuredImageUrl' : [] | [string],
  'longitude' : [] | [number],
}
export interface UpdatePropertyInput {
  'latitude' : [] | [number],
  'title' : [] | [string],
  'propertyType' : [] | [PropertyType],
  'bedrooms' : [] | [bigint],
  'city' : [] | [string],
  'neighborhood' : [] | [string],
  'sqft' : [] | [bigint],
  'description' : [] | [string],
  'amenities' : [] | [Array<string>],
  'longitude' : [] | [number],
  'address' : [] | [string],
  'bathrooms' : [] | [bigint],
  'price' : [] | [bigint],
  'photos' : [] | [Array<string>],
}
export interface UpdateUserInput {
  'name' : [] | [string],
  'email' : [] | [string],
  'avatarUrl' : [] | [string],
  'phone' : [] | [string],
}
export interface User {
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'isVerified' : boolean,
  'avatarUrl' : string,
  'phone' : string,
  'principalId' : UserId,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'agent' : null } |
  { 'buyer' : null };
export interface _SERVICE {
  'activateUser' : ActorMethod<[UserId], boolean>,
  'addToCompare' : ActorMethod<[PropertyId], undefined>,
  'approveProperty' : ActorMethod<[PropertyId, string], [] | [Property]>,
  'createBlogPost' : ActorMethod<[CreateBlogPostInput], BlogPost>,
  'createInquiry' : ActorMethod<[CreateInquiryInput], Inquiry>,
  'createLocation' : ActorMethod<[CreateLocationInput], Location>,
  'createProperty' : ActorMethod<[CreatePropertyInput], Property>,
  'deactivateUser' : ActorMethod<[UserId], boolean>,
  'deleteBlogPost' : ActorMethod<[BlogPostId], boolean>,
  'deleteProperty' : ActorMethod<[PropertyId], boolean>,
  'flagContent' : ActorMethod<[CreateFlagInput], FlaggedContent>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAgentListings' : ActorMethod<[UserId], Array<Property>>,
  'getBlogPost' : ActorMethod<[BlogPostId], [] | [BlogPost]>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getCompareList' : ActorMethod<[], Array<Property>>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getInquiry' : ActorMethod<[InquiryId], [] | [Inquiry]>,
  'getLocation' : ActorMethod<[LocationId], [] | [Location]>,
  'getLocationBySlug' : ActorMethod<[string], [] | [Location]>,
  'getPropertiesByCity' : ActorMethod<[string], Array<Property>>,
  'getPropertiesByNeighborhood' : ActorMethod<[string], Array<Property>>,
  'getPropertiesByType' : ActorMethod<[PropertyType], Array<Property>>,
  'getProperty' : ActorMethod<[PropertyId], [] | [Property]>,
  'getSavedProperties' : ActorMethod<[], Array<Property>>,
  'getSimilarProperties' : ActorMethod<[PropertyId], Array<Property>>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getUserByPrincipal' : ActorMethod<[], [] | [User]>,
  'listAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'listAllUsers' : ActorMethod<[], Array<User>>,
  'listBlogPosts' : ActorMethod<
    [[] | [BlogCategory], [] | [boolean]],
    Array<BlogPost>
  >,
  'listFlaggedContent' : ActorMethod<[], Array<FlaggedContent>>,
  'listInquiryByProperty' : ActorMethod<[PropertyId], Array<Inquiry>>,
  'listInquiryByUser' : ActorMethod<[], Array<Inquiry>>,
  'listLocations' : ActorMethod<[], Array<Location>>,
  'listNeighborhoodsByCity' : ActorMethod<[LocationId], Array<Location>>,
  'listProperties' : ActorMethod<[bigint, bigint], Page>,
  'registerUser' : ActorMethod<[RegisterUserInput], User>,
  'rejectProperty' : ActorMethod<[PropertyId, string], [] | [Property]>,
  'removeFromCompare' : ActorMethod<[PropertyId], undefined>,
  'reviewFlaggedContent' : ActorMethod<
    [FlagId, FlagAction],
    [] | [FlaggedContent]
  >,
  'saveProperty' : ActorMethod<[PropertyId], undefined>,
  'searchProperties' : ActorMethod<[SearchFilters], Page>,
  'setUserRole' : ActorMethod<[UserId, UserRole], [] | [User]>,
  'unsaveProperty' : ActorMethod<[PropertyId], undefined>,
  'updateBlogPost' : ActorMethod<
    [BlogPostId, UpdateBlogPostInput],
    [] | [BlogPost]
  >,
  'updateInquiryStatus' : ActorMethod<
    [InquiryId, InquiryStatus],
    [] | [Inquiry]
  >,
  'updateLocation' : ActorMethod<
    [LocationId, UpdateLocationInput],
    [] | [Location]
  >,
  'updateProperty' : ActorMethod<
    [PropertyId, UpdatePropertyInput],
    [] | [Property]
  >,
  'updateUser' : ActorMethod<[UpdateUserInput], [] | [User]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];