/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const PropertyId = IDL.Nat;
export const PropertyStatus = IDL.Variant({
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'studio' : IDL.Null,
  'commercial' : IDL.Null,
  'house' : IDL.Null,
  'villa' : IDL.Null,
  'apartment' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Property = IDL.Record({
  'id' : PropertyId,
  'status' : PropertyStatus,
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'verificationSource' : IDL.Opt(IDL.Text),
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'city' : IDL.Text,
  'neighborhood' : IDL.Text,
  'createdAt' : Timestamp,
  'sqft' : IDL.Nat,
  'description' : IDL.Text,
  'agentId' : UserId,
  'amenities' : IDL.Vec(IDL.Text),
  'updatedAt' : Timestamp,
  'isFeatured' : IDL.Bool,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'verifiedAt' : IDL.Opt(Timestamp),
  'photos' : IDL.Vec(IDL.Text),
});
export const BlogCategory = IDL.Variant({
  'news' : IDL.Null,
  'marketTrends' : IDL.Null,
  'buyingGuide' : IDL.Null,
  'rentalGuide' : IDL.Null,
});
export const CreateBlogPostInput = IDL.Record({
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'featuredImageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : BlogCategory,
});
export const BlogPostId = IDL.Nat;
export const BlogPost = IDL.Record({
  'id' : BlogPostId,
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Opt(Timestamp),
  'updatedAt' : Timestamp,
  'featuredImageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : BlogCategory,
});
export const InquiryType = IDL.Variant({
  'requestCallback' : IDL.Null,
  'scheduleVisit' : IDL.Null,
  'contactAgent' : IDL.Null,
});
export const CreateInquiryInput = IDL.Record({
  'inquiryType' : InquiryType,
  'propertyId' : PropertyId,
  'message' : IDL.Text,
  'preferredTime' : IDL.Opt(IDL.Text),
  'contactDetails' : IDL.Text,
});
export const InquiryId = IDL.Nat;
export const InquiryStatus = IDL.Variant({
  'closed' : IDL.Null,
  'responded' : IDL.Null,
  'pending' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'status' : InquiryStatus,
  'userId' : UserId,
  'inquiryType' : InquiryType,
  'createdAt' : Timestamp,
  'propertyId' : PropertyId,
  'message' : IDL.Text,
  'preferredTime' : IDL.Opt(IDL.Text),
  'contactDetails' : IDL.Text,
});
export const LocationId = IDL.Nat;
export const LocationType = IDL.Variant({
  'city' : IDL.Null,
  'neighborhood' : IDL.Null,
});
export const CreateLocationInput = IDL.Record({
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'featuredImageUrl' : IDL.Text,
  'longitude' : IDL.Float64,
  'parentId' : IDL.Opt(LocationId),
  'locationType' : LocationType,
});
export const Location = IDL.Record({
  'id' : LocationId,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'featuredImageUrl' : IDL.Text,
  'longitude' : IDL.Float64,
  'parentId' : IDL.Opt(LocationId),
  'locationType' : LocationType,
});
export const CreatePropertyInput = IDL.Record({
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'city' : IDL.Text,
  'neighborhood' : IDL.Text,
  'sqft' : IDL.Nat,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(IDL.Text),
});
export const ContentType = IDL.Variant({
  'blogPost' : IDL.Null,
  'property' : IDL.Null,
});
export const CreateFlagInput = IDL.Record({
  'contentId' : IDL.Nat,
  'contentType' : ContentType,
  'reason' : IDL.Text,
});
export const FlagId = IDL.Nat;
export const FlagStatus = IDL.Variant({
  'pending' : IDL.Null,
  'reviewed' : IDL.Null,
  'removed' : IDL.Null,
});
export const FlaggedContent = IDL.Record({
  'id' : FlagId,
  'status' : FlagStatus,
  'contentId' : IDL.Nat,
  'contentType' : ContentType,
  'createdAt' : Timestamp,
  'reportedBy' : UserId,
  'reason' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'activeUsers' : IDL.Nat,
  'pendingApprovals' : IDL.Nat,
  'totalBlogPosts' : IDL.Nat,
  'totalListings' : IDL.Nat,
  'totalInquiries' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'agent' : IDL.Null,
  'buyer' : IDL.Null,
});
export const User = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
  'avatarUrl' : IDL.Text,
  'phone' : IDL.Text,
  'principalId' : UserId,
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Property),
});
export const RegisterUserInput = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'phone' : IDL.Text,
});
export const FlagAction = IDL.Variant({
  'remove' : IDL.Null,
  'dismiss' : IDL.Null,
});
export const SearchFilters = IDL.Record({
  'propertyType' : IDL.Opt(PropertyType),
  'city' : IDL.Opt(IDL.Text),
  'neighborhood' : IDL.Opt(IDL.Text),
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'amenities' : IDL.Opt(IDL.Vec(IDL.Text)),
  'minBedrooms' : IDL.Opt(IDL.Nat),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'maxBedrooms' : IDL.Opt(IDL.Nat),
  'keyword' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
  'minBathrooms' : IDL.Opt(IDL.Nat),
});
export const UpdateBlogPostInput = IDL.Record({
  'metaDescription' : IDL.Opt(IDL.Text),
  'title' : IDL.Opt(IDL.Text),
  'content' : IDL.Opt(IDL.Text),
  'isPublished' : IDL.Opt(IDL.Bool),
  'slug' : IDL.Opt(IDL.Text),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(BlogCategory),
});
export const UpdateLocationInput = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'name' : IDL.Opt(IDL.Text),
  'slug' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'longitude' : IDL.Opt(IDL.Float64),
});
export const UpdatePropertyInput = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'title' : IDL.Opt(IDL.Text),
  'propertyType' : IDL.Opt(PropertyType),
  'bedrooms' : IDL.Opt(IDL.Nat),
  'city' : IDL.Opt(IDL.Text),
  'neighborhood' : IDL.Opt(IDL.Text),
  'sqft' : IDL.Opt(IDL.Nat),
  'description' : IDL.Opt(IDL.Text),
  'amenities' : IDL.Opt(IDL.Vec(IDL.Text)),
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Opt(IDL.Text),
  'bathrooms' : IDL.Opt(IDL.Nat),
  'price' : IDL.Opt(IDL.Nat),
  'photos' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const UpdateUserInput = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'activateUser' : IDL.Func([UserId], [IDL.Bool], []),
  'addToCompare' : IDL.Func([PropertyId], [], []),
  'approveProperty' : IDL.Func([PropertyId, IDL.Text], [IDL.Opt(Property)], []),
  'createBlogPost' : IDL.Func([CreateBlogPostInput], [BlogPost], []),
  'createInquiry' : IDL.Func([CreateInquiryInput], [Inquiry], []),
  'createLocation' : IDL.Func([CreateLocationInput], [Location], []),
  'createProperty' : IDL.Func([CreatePropertyInput], [Property], []),
  'deactivateUser' : IDL.Func([UserId], [IDL.Bool], []),
  'deleteBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
  'deleteProperty' : IDL.Func([PropertyId], [IDL.Bool], []),
  'flagContent' : IDL.Func([CreateFlagInput], [FlaggedContent], []),
  'getAdminStats' : IDL.Func([], [AdminStats], []),
  'getAgentListings' : IDL.Func([UserId], [IDL.Vec(Property)], ['query']),
  'getBlogPost' : IDL.Func([BlogPostId], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCompareList' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getInquiry' : IDL.Func([InquiryId], [IDL.Opt(Inquiry)], ['query']),
  'getLocation' : IDL.Func([LocationId], [IDL.Opt(Location)], ['query']),
  'getLocationBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
  'getPropertiesByCity' : IDL.Func([IDL.Text], [IDL.Vec(Property)], ['query']),
  'getPropertiesByNeighborhood' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByType' : IDL.Func(
      [PropertyType],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getProperty' : IDL.Func([PropertyId], [IDL.Opt(Property)], ['query']),
  'getSavedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getSimilarProperties' : IDL.Func(
      [PropertyId],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getUserByPrincipal' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'listAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], []),
  'listAllUsers' : IDL.Func([], [IDL.Vec(User)], []),
  'listBlogPosts' : IDL.Func(
      [IDL.Opt(BlogCategory), IDL.Opt(IDL.Bool)],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'listFlaggedContent' : IDL.Func([], [IDL.Vec(FlaggedContent)], []),
  'listInquiryByProperty' : IDL.Func(
      [PropertyId],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'listInquiryByUser' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'listLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'listNeighborhoodsByCity' : IDL.Func(
      [LocationId],
      [IDL.Vec(Location)],
      ['query'],
    ),
  'listProperties' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
  'registerUser' : IDL.Func([RegisterUserInput], [User], []),
  'rejectProperty' : IDL.Func([PropertyId, IDL.Text], [IDL.Opt(Property)], []),
  'removeFromCompare' : IDL.Func([PropertyId], [], []),
  'reviewFlaggedContent' : IDL.Func(
      [FlagId, FlagAction],
      [IDL.Opt(FlaggedContent)],
      [],
    ),
  'saveProperty' : IDL.Func([PropertyId], [], []),
  'searchProperties' : IDL.Func([SearchFilters], [Page], ['query']),
  'setUserRole' : IDL.Func([UserId, UserRole], [IDL.Opt(User)], []),
  'unsaveProperty' : IDL.Func([PropertyId], [], []),
  'updateBlogPost' : IDL.Func(
      [BlogPostId, UpdateBlogPostInput],
      [IDL.Opt(BlogPost)],
      [],
    ),
  'updateInquiryStatus' : IDL.Func(
      [InquiryId, InquiryStatus],
      [IDL.Opt(Inquiry)],
      [],
    ),
  'updateLocation' : IDL.Func(
      [LocationId, UpdateLocationInput],
      [IDL.Opt(Location)],
      [],
    ),
  'updateProperty' : IDL.Func(
      [PropertyId, UpdatePropertyInput],
      [IDL.Opt(Property)],
      [],
    ),
  'updateUser' : IDL.Func([UpdateUserInput], [IDL.Opt(User)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const PropertyId = IDL.Nat;
  const PropertyStatus = IDL.Variant({
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'studio' : IDL.Null,
    'commercial' : IDL.Null,
    'house' : IDL.Null,
    'villa' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Property = IDL.Record({
    'id' : PropertyId,
    'status' : PropertyStatus,
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'verificationSource' : IDL.Opt(IDL.Text),
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'city' : IDL.Text,
    'neighborhood' : IDL.Text,
    'createdAt' : Timestamp,
    'sqft' : IDL.Nat,
    'description' : IDL.Text,
    'agentId' : UserId,
    'amenities' : IDL.Vec(IDL.Text),
    'updatedAt' : Timestamp,
    'isFeatured' : IDL.Bool,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'verifiedAt' : IDL.Opt(Timestamp),
    'photos' : IDL.Vec(IDL.Text),
  });
  const BlogCategory = IDL.Variant({
    'news' : IDL.Null,
    'marketTrends' : IDL.Null,
    'buyingGuide' : IDL.Null,
    'rentalGuide' : IDL.Null,
  });
  const CreateBlogPostInput = IDL.Record({
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'featuredImageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : BlogCategory,
  });
  const BlogPostId = IDL.Nat;
  const BlogPost = IDL.Record({
    'id' : BlogPostId,
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Opt(Timestamp),
    'updatedAt' : Timestamp,
    'featuredImageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : BlogCategory,
  });
  const InquiryType = IDL.Variant({
    'requestCallback' : IDL.Null,
    'scheduleVisit' : IDL.Null,
    'contactAgent' : IDL.Null,
  });
  const CreateInquiryInput = IDL.Record({
    'inquiryType' : InquiryType,
    'propertyId' : PropertyId,
    'message' : IDL.Text,
    'preferredTime' : IDL.Opt(IDL.Text),
    'contactDetails' : IDL.Text,
  });
  const InquiryId = IDL.Nat;
  const InquiryStatus = IDL.Variant({
    'closed' : IDL.Null,
    'responded' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'status' : InquiryStatus,
    'userId' : UserId,
    'inquiryType' : InquiryType,
    'createdAt' : Timestamp,
    'propertyId' : PropertyId,
    'message' : IDL.Text,
    'preferredTime' : IDL.Opt(IDL.Text),
    'contactDetails' : IDL.Text,
  });
  const LocationId = IDL.Nat;
  const LocationType = IDL.Variant({
    'city' : IDL.Null,
    'neighborhood' : IDL.Null,
  });
  const CreateLocationInput = IDL.Record({
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'featuredImageUrl' : IDL.Text,
    'longitude' : IDL.Float64,
    'parentId' : IDL.Opt(LocationId),
    'locationType' : LocationType,
  });
  const Location = IDL.Record({
    'id' : LocationId,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'featuredImageUrl' : IDL.Text,
    'longitude' : IDL.Float64,
    'parentId' : IDL.Opt(LocationId),
    'locationType' : LocationType,
  });
  const CreatePropertyInput = IDL.Record({
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'city' : IDL.Text,
    'neighborhood' : IDL.Text,
    'sqft' : IDL.Nat,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(IDL.Text),
  });
  const ContentType = IDL.Variant({
    'blogPost' : IDL.Null,
    'property' : IDL.Null,
  });
  const CreateFlagInput = IDL.Record({
    'contentId' : IDL.Nat,
    'contentType' : ContentType,
    'reason' : IDL.Text,
  });
  const FlagId = IDL.Nat;
  const FlagStatus = IDL.Variant({
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
    'removed' : IDL.Null,
  });
  const FlaggedContent = IDL.Record({
    'id' : FlagId,
    'status' : FlagStatus,
    'contentId' : IDL.Nat,
    'contentType' : ContentType,
    'createdAt' : Timestamp,
    'reportedBy' : UserId,
    'reason' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'activeUsers' : IDL.Nat,
    'pendingApprovals' : IDL.Nat,
    'totalBlogPosts' : IDL.Nat,
    'totalListings' : IDL.Nat,
    'totalInquiries' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'agent' : IDL.Null,
    'buyer' : IDL.Null,
  });
  const User = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
    'avatarUrl' : IDL.Text,
    'phone' : IDL.Text,
    'principalId' : UserId,
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Property),
  });
  const RegisterUserInput = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FlagAction = IDL.Variant({ 'remove' : IDL.Null, 'dismiss' : IDL.Null });
  const SearchFilters = IDL.Record({
    'propertyType' : IDL.Opt(PropertyType),
    'city' : IDL.Opt(IDL.Text),
    'neighborhood' : IDL.Opt(IDL.Text),
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'amenities' : IDL.Opt(IDL.Vec(IDL.Text)),
    'minBedrooms' : IDL.Opt(IDL.Nat),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'maxBedrooms' : IDL.Opt(IDL.Nat),
    'keyword' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
    'minBathrooms' : IDL.Opt(IDL.Nat),
  });
  const UpdateBlogPostInput = IDL.Record({
    'metaDescription' : IDL.Opt(IDL.Text),
    'title' : IDL.Opt(IDL.Text),
    'content' : IDL.Opt(IDL.Text),
    'isPublished' : IDL.Opt(IDL.Bool),
    'slug' : IDL.Opt(IDL.Text),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(BlogCategory),
  });
  const UpdateLocationInput = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'name' : IDL.Opt(IDL.Text),
    'slug' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'longitude' : IDL.Opt(IDL.Float64),
  });
  const UpdatePropertyInput = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'title' : IDL.Opt(IDL.Text),
    'propertyType' : IDL.Opt(PropertyType),
    'bedrooms' : IDL.Opt(IDL.Nat),
    'city' : IDL.Opt(IDL.Text),
    'neighborhood' : IDL.Opt(IDL.Text),
    'sqft' : IDL.Opt(IDL.Nat),
    'description' : IDL.Opt(IDL.Text),
    'amenities' : IDL.Opt(IDL.Vec(IDL.Text)),
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Opt(IDL.Text),
    'bathrooms' : IDL.Opt(IDL.Nat),
    'price' : IDL.Opt(IDL.Nat),
    'photos' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const UpdateUserInput = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'activateUser' : IDL.Func([UserId], [IDL.Bool], []),
    'addToCompare' : IDL.Func([PropertyId], [], []),
    'approveProperty' : IDL.Func(
        [PropertyId, IDL.Text],
        [IDL.Opt(Property)],
        [],
      ),
    'createBlogPost' : IDL.Func([CreateBlogPostInput], [BlogPost], []),
    'createInquiry' : IDL.Func([CreateInquiryInput], [Inquiry], []),
    'createLocation' : IDL.Func([CreateLocationInput], [Location], []),
    'createProperty' : IDL.Func([CreatePropertyInput], [Property], []),
    'deactivateUser' : IDL.Func([UserId], [IDL.Bool], []),
    'deleteBlogPost' : IDL.Func([BlogPostId], [IDL.Bool], []),
    'deleteProperty' : IDL.Func([PropertyId], [IDL.Bool], []),
    'flagContent' : IDL.Func([CreateFlagInput], [FlaggedContent], []),
    'getAdminStats' : IDL.Func([], [AdminStats], []),
    'getAgentListings' : IDL.Func([UserId], [IDL.Vec(Property)], ['query']),
    'getBlogPost' : IDL.Func([BlogPostId], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCompareList' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getInquiry' : IDL.Func([InquiryId], [IDL.Opt(Inquiry)], ['query']),
    'getLocation' : IDL.Func([LocationId], [IDL.Opt(Location)], ['query']),
    'getLocationBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
    'getPropertiesByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByNeighborhood' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByType' : IDL.Func(
        [PropertyType],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getProperty' : IDL.Func([PropertyId], [IDL.Opt(Property)], ['query']),
    'getSavedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getSimilarProperties' : IDL.Func(
        [PropertyId],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getUserByPrincipal' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'listAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], []),
    'listAllUsers' : IDL.Func([], [IDL.Vec(User)], []),
    'listBlogPosts' : IDL.Func(
        [IDL.Opt(BlogCategory), IDL.Opt(IDL.Bool)],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'listFlaggedContent' : IDL.Func([], [IDL.Vec(FlaggedContent)], []),
    'listInquiryByProperty' : IDL.Func(
        [PropertyId],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'listInquiryByUser' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'listLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'listNeighborhoodsByCity' : IDL.Func(
        [LocationId],
        [IDL.Vec(Location)],
        ['query'],
      ),
    'listProperties' : IDL.Func([IDL.Nat, IDL.Nat], [Page], ['query']),
    'registerUser' : IDL.Func([RegisterUserInput], [User], []),
    'rejectProperty' : IDL.Func(
        [PropertyId, IDL.Text],
        [IDL.Opt(Property)],
        [],
      ),
    'removeFromCompare' : IDL.Func([PropertyId], [], []),
    'reviewFlaggedContent' : IDL.Func(
        [FlagId, FlagAction],
        [IDL.Opt(FlaggedContent)],
        [],
      ),
    'saveProperty' : IDL.Func([PropertyId], [], []),
    'searchProperties' : IDL.Func([SearchFilters], [Page], ['query']),
    'setUserRole' : IDL.Func([UserId, UserRole], [IDL.Opt(User)], []),
    'unsaveProperty' : IDL.Func([PropertyId], [], []),
    'updateBlogPost' : IDL.Func(
        [BlogPostId, UpdateBlogPostInput],
        [IDL.Opt(BlogPost)],
        [],
      ),
    'updateInquiryStatus' : IDL.Func(
        [InquiryId, InquiryStatus],
        [IDL.Opt(Inquiry)],
        [],
      ),
    'updateLocation' : IDL.Func(
        [LocationId, UpdateLocationInput],
        [IDL.Opt(Location)],
        [],
      ),
    'updateProperty' : IDL.Func(
        [PropertyId, UpdatePropertyInput],
        [IDL.Opt(Property)],
        [],
      ),
    'updateUser' : IDL.Func([UpdateUserInput], [IDL.Opt(User)], []),
  });
};

export const init = ({ IDL }) => { return []; };