/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    id: LocationId;
    latitude: number;
    name: string;
    slug: string;
    description: string;
    featuredImageUrl: string;
    longitude: number;
    parentId?: LocationId;
    locationType: LocationType;
}
export type Timestamp = bigint;
export interface Property {
    id: PropertyId;
    status: PropertyStatus;
    latitude: number;
    title: string;
    verificationSource?: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    city: string;
    neighborhood: string;
    createdAt: Timestamp;
    sqft: bigint;
    description: string;
    agentId: UserId;
    amenities: Array<string>;
    updatedAt: Timestamp;
    isFeatured: boolean;
    longitude: number;
    address: string;
    bathrooms: bigint;
    price: bigint;
    verifiedAt?: Timestamp;
    photos: Array<string>;
}
export type FlagId = bigint;
export interface Page {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Property>;
}
export interface UpdateLocationInput {
    latitude?: number;
    name?: string;
    slug?: string;
    description?: string;
    featuredImageUrl?: string;
    longitude?: number;
}
export interface CreateBlogPostInput {
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    tags: Array<string>;
    featuredImageUrl: string;
    excerpt: string;
    category: BlogCategory;
}
export interface UpdatePropertyInput {
    latitude?: number;
    title?: string;
    propertyType?: PropertyType;
    bedrooms?: bigint;
    city?: string;
    neighborhood?: string;
    sqft?: bigint;
    description?: string;
    amenities?: Array<string>;
    longitude?: number;
    address?: string;
    bathrooms?: bigint;
    price?: bigint;
    photos?: Array<string>;
}
export interface FlaggedContent {
    id: FlagId;
    status: FlagStatus;
    contentId: bigint;
    contentType: ContentType;
    createdAt: Timestamp;
    reportedBy: UserId;
    reason: string;
}
export interface SearchFilters {
    propertyType?: PropertyType;
    city?: string;
    neighborhood?: string;
    page: bigint;
    pageSize: bigint;
    amenities?: Array<string>;
    minBedrooms?: bigint;
    maxPrice?: bigint;
    maxBedrooms?: bigint;
    keyword?: string;
    minPrice?: bigint;
    minBathrooms?: bigint;
}
export interface CreateInquiryInput {
    inquiryType: InquiryType;
    propertyId: PropertyId;
    message: string;
    preferredTime?: string;
    contactDetails: string;
}
export interface BlogPost {
    id: BlogPostId;
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    authorId: UserId;
    createdAt: Timestamp;
    slug: string;
    tags: Array<string>;
    publishedAt?: Timestamp;
    updatedAt: Timestamp;
    featuredImageUrl: string;
    excerpt: string;
    category: BlogCategory;
}
export interface UpdateUserInput {
    name?: string;
    email?: string;
    avatarUrl?: string;
    phone?: string;
}
export interface User {
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    isActive: boolean;
    email: string;
    isVerified: boolean;
    avatarUrl: string;
    phone: string;
    principalId: UserId;
}
export interface CreatePropertyInput {
    latitude: number;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    city: string;
    neighborhood: string;
    sqft: bigint;
    description: string;
    amenities: Array<string>;
    longitude: number;
    address: string;
    bathrooms: bigint;
    price: bigint;
    photos: Array<string>;
}
export interface UpdateBlogPostInput {
    metaDescription?: string;
    title?: string;
    content?: string;
    isPublished?: boolean;
    slug?: string;
    tags?: Array<string>;
    featuredImageUrl?: string;
    excerpt?: string;
    category?: BlogCategory;
}
export interface CreateFlagInput {
    contentId: bigint;
    contentType: ContentType;
    reason: string;
}
export interface CreateLocationInput {
    latitude: number;
    name: string;
    slug: string;
    description: string;
    featuredImageUrl: string;
    longitude: number;
    parentId?: LocationId;
    locationType: LocationType;
}
export type UserId = Principal;
export interface RegisterUserInput {
    name: string;
    role: UserRole;
    email: string;
    avatarUrl: string;
    phone: string;
}
export type InquiryId = bigint;
export type PropertyId = bigint;
export type BlogPostId = bigint;
export interface AdminStats {
    activeUsers: bigint;
    pendingApprovals: bigint;
    totalBlogPosts: bigint;
    totalListings: bigint;
    totalInquiries: bigint;
}
export interface Inquiry {
    id: InquiryId;
    status: InquiryStatus;
    userId: UserId;
    inquiryType: InquiryType;
    createdAt: Timestamp;
    propertyId: PropertyId;
    message: string;
    preferredTime?: string;
    contactDetails: string;
}
export type LocationId = bigint;
export enum BlogCategory {
    news = "news",
    marketTrends = "marketTrends",
    buyingGuide = "buyingGuide",
    rentalGuide = "rentalGuide"
}
export enum ContentType {
    blogPost = "blogPost",
    property = "property"
}
export enum FlagAction {
    remove = "remove",
    dismiss = "dismiss"
}
export enum FlagStatus {
    pending = "pending",
    reviewed = "reviewed",
    removed = "removed"
}
export enum InquiryStatus {
    closed = "closed",
    responded = "responded",
    pending = "pending"
}
export enum InquiryType {
    requestCallback = "requestCallback",
    scheduleVisit = "scheduleVisit",
    contactAgent = "contactAgent"
}
export enum LocationType {
    city = "city",
    neighborhood = "neighborhood"
}
export enum PropertyStatus {
    pending = "pending",
    inactive = "inactive",
    approved = "approved",
    rejected = "rejected"
}
export enum PropertyType {
    studio = "studio",
    commercial = "commercial",
    house = "house",
    villa = "villa",
    apartment = "apartment"
}
export enum UserRole {
    admin = "admin",
    agent = "agent",
    buyer = "buyer"
}
export interface backendInterface {
    activateUser(principalId: UserId): Promise<boolean>;
    addToCompare(propertyId: PropertyId): Promise<void>;
    approveProperty(propertyId: PropertyId, verificationSource: string): Promise<Property | null>;
    createBlogPost(input: CreateBlogPostInput): Promise<BlogPost>;
    createInquiry(input: CreateInquiryInput): Promise<Inquiry>;
    createLocation(input: CreateLocationInput): Promise<Location>;
    createProperty(input: CreatePropertyInput): Promise<Property>;
    deactivateUser(principalId: UserId): Promise<boolean>;
    deleteBlogPost(postId: BlogPostId): Promise<boolean>;
    deleteProperty(propertyId: PropertyId): Promise<boolean>;
    flagContent(input: CreateFlagInput): Promise<FlaggedContent>;
    getAdminStats(): Promise<AdminStats>;
    getAgentListings(agentId: UserId): Promise<Array<Property>>;
    getBlogPost(postId: BlogPostId): Promise<BlogPost | null>;
    getBlogPostBySlug(slug: string): Promise<BlogPost | null>;
    getCompareList(): Promise<Array<Property>>;
    getFeaturedProperties(): Promise<Array<Property>>;
    getInquiry(inquiryId: InquiryId): Promise<Inquiry | null>;
    getLocation(locationId: LocationId): Promise<Location | null>;
    getLocationBySlug(slug: string): Promise<Location | null>;
    getPropertiesByCity(city: string): Promise<Array<Property>>;
    getPropertiesByNeighborhood(neighborhood: string): Promise<Array<Property>>;
    getPropertiesByType(propertyType: PropertyType): Promise<Array<Property>>;
    getProperty(propertyId: PropertyId): Promise<Property | null>;
    getSavedProperties(): Promise<Array<Property>>;
    getSimilarProperties(propertyId: PropertyId): Promise<Array<Property>>;
    getUser(principalId: UserId): Promise<User | null>;
    getUserByPrincipal(): Promise<User | null>;
    listAllInquiries(): Promise<Array<Inquiry>>;
    listAllUsers(): Promise<Array<User>>;
    listBlogPosts(category: BlogCategory | null, isPublished: boolean | null): Promise<Array<BlogPost>>;
    listFlaggedContent(): Promise<Array<FlaggedContent>>;
    listInquiryByProperty(propertyId: PropertyId): Promise<Array<Inquiry>>;
    listInquiryByUser(): Promise<Array<Inquiry>>;
    listLocations(): Promise<Array<Location>>;
    listNeighborhoodsByCity(cityId: LocationId): Promise<Array<Location>>;
    listProperties(page: bigint, pageSize: bigint): Promise<Page>;
    registerUser(input: RegisterUserInput): Promise<User>;
    rejectProperty(propertyId: PropertyId, reason: string): Promise<Property | null>;
    removeFromCompare(propertyId: PropertyId): Promise<void>;
    reviewFlaggedContent(flagId: FlagId, action: FlagAction): Promise<FlaggedContent | null>;
    saveProperty(propertyId: PropertyId): Promise<void>;
    searchProperties(filters: SearchFilters): Promise<Page>;
    setUserRole(principalId: UserId, role: UserRole): Promise<User | null>;
    unsaveProperty(propertyId: PropertyId): Promise<void>;
    updateBlogPost(postId: BlogPostId, input: UpdateBlogPostInput): Promise<BlogPost | null>;
    updateInquiryStatus(inquiryId: InquiryId, status: InquiryStatus): Promise<Inquiry | null>;
    updateLocation(locationId: LocationId, input: UpdateLocationInput): Promise<Location | null>;
    updateProperty(propertyId: PropertyId, input: UpdatePropertyInput): Promise<Property | null>;
    updateUser(input: UpdateUserInput): Promise<User | null>;
}
import type { BlogCategory as _BlogCategory, BlogPost as _BlogPost, BlogPostId as _BlogPostId, ContentType as _ContentType, CreateBlogPostInput as _CreateBlogPostInput, CreateFlagInput as _CreateFlagInput, CreateInquiryInput as _CreateInquiryInput, CreateLocationInput as _CreateLocationInput, CreatePropertyInput as _CreatePropertyInput, FlagAction as _FlagAction, FlagId as _FlagId, FlagStatus as _FlagStatus, FlaggedContent as _FlaggedContent, Inquiry as _Inquiry, InquiryId as _InquiryId, InquiryStatus as _InquiryStatus, InquiryType as _InquiryType, Location as _Location, LocationId as _LocationId, LocationType as _LocationType, Page as _Page, Property as _Property, PropertyId as _PropertyId, PropertyStatus as _PropertyStatus, PropertyType as _PropertyType, RegisterUserInput as _RegisterUserInput, SearchFilters as _SearchFilters, Timestamp as _Timestamp, UpdateBlogPostInput as _UpdateBlogPostInput, UpdateLocationInput as _UpdateLocationInput, UpdatePropertyInput as _UpdatePropertyInput, UpdateUserInput as _UpdateUserInput, User as _User, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async activateUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.activateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateUser(arg0);
            return result;
        }
    }
    async addToCompare(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCompare(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCompare(arg0);
            return result;
        }
    }
    async approveProperty(arg0: PropertyId, arg1: string): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.approveProperty(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveProperty(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBlogPost(arg0: CreateBlogPostInput): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(to_candid_CreateBlogPostInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlogPost_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(to_candid_CreateBlogPostInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlogPost_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInquiry(arg0: CreateInquiryInput): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.createInquiry(to_candid_CreateInquiryInput_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Inquiry_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInquiry(to_candid_CreateInquiryInput_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Inquiry_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLocation(arg0: CreateLocationInput): Promise<Location> {
        if (this.processError) {
            try {
                const result = await this.actor.createLocation(to_candid_CreateLocationInput_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Location_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLocation(to_candid_CreateLocationInput_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Location_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProperty(arg0: CreatePropertyInput): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.createProperty(to_candid_CreatePropertyInput_n37(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Property_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProperty(to_candid_CreatePropertyInput_n37(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Property_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: BlogPostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteProperty(arg0: PropertyId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async flagContent(arg0: CreateFlagInput): Promise<FlaggedContent> {
        if (this.processError) {
            try {
                const result = await this.actor.flagContent(to_candid_CreateFlagInput_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FlaggedContent_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagContent(to_candid_CreateFlagInput_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FlaggedContent_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAgentListings(arg0: UserId): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentListings(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentListings(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: BlogPostId): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostBySlug(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostBySlug(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompareList(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompareList();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompareList();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProperties();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProperties();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiry(arg0: InquiryId): Promise<Inquiry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiry(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiry(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocation(arg0: LocationId): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocation(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocation(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocationBySlug(arg0: string): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationBySlug(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationBySlug(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByCity(arg0: string): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByCity(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByCity(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByNeighborhood(arg0: string): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByNeighborhood(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByNeighborhood(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByType(arg0: PropertyType): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByType(to_candid_PropertyType_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByType(to_candid_PropertyType_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: PropertyId): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedProperties();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedProperties();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSimilarProperties(arg0: PropertyId): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSimilarProperties(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSimilarProperties(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByPrincipal(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPrincipal();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPrincipal();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllInquiries();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllInquiries();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBlogPosts(arg0: BlogCategory | null, arg1: boolean | null): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPosts(to_candid_opt_n62(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPosts(to_candid_opt_n62(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n63(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFlaggedContent(): Promise<Array<FlaggedContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFlaggedContent();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFlaggedContent();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInquiryByProperty(arg0: PropertyId): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInquiryByProperty(arg0);
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInquiryByProperty(arg0);
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInquiryByUser(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInquiryByUser();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInquiryByUser();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLocations(): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLocations();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLocations();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNeighborhoodsByCity(arg0: LocationId): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNeighborhoodsByCity(arg0);
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNeighborhoodsByCity(arg0);
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProperties(arg0: bigint, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.listProperties(arg0, arg1);
                return from_candid_Page_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProperties(arg0, arg1);
            return from_candid_Page_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterUserInput): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterUserInput_n69(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterUserInput_n69(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectProperty(arg0: PropertyId, arg1: string): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectProperty(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectProperty(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCompare(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCompare(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCompare(arg0);
            return result;
        }
    }
    async reviewFlaggedContent(arg0: FlagId, arg1: FlagAction): Promise<FlaggedContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewFlaggedContent(arg0, to_candid_FlagAction_n73(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewFlaggedContent(arg0, to_candid_FlagAction_n73(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveProperty(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProperty(arg0);
            return result;
        }
    }
    async searchProperties(arg0: SearchFilters): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProperties(to_candid_SearchFilters_n76(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Page_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProperties(to_candid_SearchFilters_n76(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Page_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: UserId, arg1: UserRole): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n71(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n71(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async unsaveProperty(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveProperty(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: BlogPostId, arg1: UpdateBlogPostInput): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, to_candid_UpdateBlogPostInput_n78(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, to_candid_UpdateBlogPostInput_n78(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInquiryStatus(arg0: InquiryId, arg1: InquiryStatus): Promise<Inquiry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n80(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n80(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLocation(arg0: LocationId, arg1: UpdateLocationInput): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocation(arg0, to_candid_UpdateLocationInput_n82(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocation(arg0, to_candid_UpdateLocationInput_n82(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProperty(arg0: PropertyId, arg1: UpdatePropertyInput): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, to_candid_UpdatePropertyInput_n84(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, to_candid_UpdatePropertyInput_n84(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UpdateUserInput): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(to_candid_UpdateUserInput_n86(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(to_candid_UpdateUserInput_n86(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BlogCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogCategory): BlogCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BlogPost_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_FlagStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlagStatus): FlagStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_FlaggedContent_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlaggedContent): FlaggedContent {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_LocationType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocationType): LocationType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Location_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Location): Location {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Page_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Page {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyStatus): PropertyStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Property_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Property {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_User_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Property | null {
    return value.length === 0 ? null : from_candid_Property_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocationId]): LocationId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Inquiry]): Inquiry | null {
    return value.length === 0 ? null : from_candid_Inquiry_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : from_candid_Location_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlaggedContent]): FlaggedContent | null {
    return value.length === 0 ? null : from_candid_FlaggedContent_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BlogPostId;
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    authorId: _UserId;
    createdAt: _Timestamp;
    slug: string;
    tags: Array<string>;
    publishedAt: [] | [_Timestamp];
    updatedAt: _Timestamp;
    featuredImageUrl: string;
    excerpt: string;
    category: _BlogCategory;
}): {
    id: BlogPostId;
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    authorId: UserId;
    createdAt: Timestamp;
    slug: string;
    tags: Array<string>;
    publishedAt?: Timestamp;
    updatedAt: Timestamp;
    featuredImageUrl: string;
    excerpt: string;
    category: BlogCategory;
} {
    return {
        id: value.id,
        metaDescription: value.metaDescription,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        authorId: value.authorId,
        createdAt: value.createdAt,
        slug: value.slug,
        tags: value.tags,
        publishedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.publishedAt)),
        updatedAt: value.updatedAt,
        featuredImageUrl: value.featuredImageUrl,
        excerpt: value.excerpt,
        category: from_candid_BlogCategory_n16(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InquiryId;
    status: _InquiryStatus;
    userId: _UserId;
    inquiryType: _InquiryType;
    createdAt: _Timestamp;
    propertyId: _PropertyId;
    message: string;
    preferredTime: [] | [string];
    contactDetails: string;
}): {
    id: InquiryId;
    status: InquiryStatus;
    userId: UserId;
    inquiryType: InquiryType;
    createdAt: Timestamp;
    propertyId: PropertyId;
    message: string;
    preferredTime?: string;
    contactDetails: string;
} {
    return {
        id: value.id,
        status: from_candid_InquiryStatus_n24(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        inquiryType: from_candid_InquiryType_n26(_uploadFile, _downloadFile, value.inquiryType),
        createdAt: value.createdAt,
        propertyId: value.propertyId,
        message: value.message,
        preferredTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.preferredTime)),
        contactDetails: value.contactDetails
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PropertyId;
    status: _PropertyStatus;
    latitude: number;
    title: string;
    verificationSource: [] | [string];
    propertyType: _PropertyType;
    bedrooms: bigint;
    city: string;
    neighborhood: string;
    createdAt: _Timestamp;
    sqft: bigint;
    description: string;
    agentId: _UserId;
    amenities: Array<string>;
    updatedAt: _Timestamp;
    isFeatured: boolean;
    longitude: number;
    address: string;
    bathrooms: bigint;
    price: bigint;
    verifiedAt: [] | [_Timestamp];
    photos: Array<string>;
}): {
    id: PropertyId;
    status: PropertyStatus;
    latitude: number;
    title: string;
    verificationSource?: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    city: string;
    neighborhood: string;
    createdAt: Timestamp;
    sqft: bigint;
    description: string;
    agentId: UserId;
    amenities: Array<string>;
    updatedAt: Timestamp;
    isFeatured: boolean;
    longitude: number;
    address: string;
    bathrooms: bigint;
    price: bigint;
    verifiedAt?: Timestamp;
    photos: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_PropertyStatus_n4(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        title: value.title,
        verificationSource: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.verificationSource)),
        propertyType: from_candid_PropertyType_n7(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        city: value.city,
        neighborhood: value.neighborhood,
        createdAt: value.createdAt,
        sqft: value.sqft,
        description: value.description,
        agentId: value.agentId,
        amenities: value.amenities,
        updatedAt: value.updatedAt,
        isFeatured: value.isFeatured,
        longitude: value.longitude,
        address: value.address,
        bathrooms: value.bathrooms,
        price: value.price,
        verifiedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.verifiedAt)),
        photos: value.photos
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LocationId;
    latitude: number;
    name: string;
    slug: string;
    description: string;
    featuredImageUrl: string;
    longitude: number;
    parentId: [] | [_LocationId];
    locationType: _LocationType;
}): {
    id: LocationId;
    latitude: number;
    name: string;
    slug: string;
    description: string;
    featuredImageUrl: string;
    longitude: number;
    parentId?: LocationId;
    locationType: LocationType;
} {
    return {
        id: value.id,
        latitude: value.latitude,
        name: value.name,
        slug: value.slug,
        description: value.description,
        featuredImageUrl: value.featuredImageUrl,
        longitude: value.longitude,
        parentId: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.parentId)),
        locationType: from_candid_LocationType_n35(_uploadFile, _downloadFile, value.locationType)
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FlagId;
    status: _FlagStatus;
    contentId: bigint;
    contentType: _ContentType;
    createdAt: _Timestamp;
    reportedBy: _UserId;
    reason: string;
}): {
    id: FlagId;
    status: FlagStatus;
    contentId: bigint;
    contentType: ContentType;
    createdAt: Timestamp;
    reportedBy: UserId;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_FlagStatus_n47(_uploadFile, _downloadFile, value.status),
        contentId: value.contentId,
        contentType: from_candid_ContentType_n49(_uploadFile, _downloadFile, value.contentType),
        createdAt: value.createdAt,
        reportedBy: value.reportedBy,
        reason: value.reason
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    isActive: boolean;
    email: string;
    isVerified: boolean;
    avatarUrl: string;
    phone: string;
    principalId: _UserId;
}): {
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    isActive: boolean;
    email: string;
    isVerified: boolean;
    avatarUrl: string;
    phone: string;
    principalId: UserId;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n58(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        isVerified: value.isVerified,
        avatarUrl: value.avatarUrl,
        phone: value.phone,
        principalId: value.principalId
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_Property>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Property>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n51(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    news: null;
} | {
    marketTrends: null;
} | {
    buyingGuide: null;
} | {
    rentalGuide: null;
}): BlogCategory {
    return "news" in value ? BlogCategory.news : "marketTrends" in value ? BlogCategory.marketTrends : "buyingGuide" in value ? BlogCategory.buyingGuide : "rentalGuide" in value ? BlogCategory.rentalGuide : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    responded: null;
} | {
    pending: null;
}): InquiryStatus {
    return "closed" in value ? InquiryStatus.closed : "responded" in value ? InquiryStatus.responded : "pending" in value ? InquiryStatus.pending : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requestCallback: null;
} | {
    scheduleVisit: null;
} | {
    contactAgent: null;
}): InquiryType {
    return "requestCallback" in value ? InquiryType.requestCallback : "scheduleVisit" in value ? InquiryType.scheduleVisit : "contactAgent" in value ? InquiryType.contactAgent : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: null;
} | {
    neighborhood: null;
}): LocationType {
    return "city" in value ? LocationType.city : "neighborhood" in value ? LocationType.neighborhood : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    reviewed: null;
} | {
    removed: null;
}): FlagStatus {
    return "pending" in value ? FlagStatus.pending : "reviewed" in value ? FlagStatus.reviewed : "removed" in value ? FlagStatus.removed : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    inactive: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PropertyStatus {
    return "pending" in value ? PropertyStatus.pending : "inactive" in value ? PropertyStatus.inactive : "approved" in value ? PropertyStatus.approved : "rejected" in value ? PropertyStatus.rejected : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blogPost: null;
} | {
    property: null;
}): ContentType {
    return "blogPost" in value ? ContentType.blogPost : "property" in value ? ContentType.property : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    agent: null;
} | {
    buyer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "agent" in value ? UserRole.agent : "buyer" in value ? UserRole.buyer : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studio: null;
} | {
    commercial: null;
} | {
    house: null;
} | {
    villa: null;
} | {
    apartment: null;
}): PropertyType {
    return "studio" in value ? PropertyType.studio : "commercial" in value ? PropertyType.commercial : "house" in value ? PropertyType.house : "villa" in value ? PropertyType.villa : "apartment" in value ? PropertyType.apartment : value;
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Array<Property> {
    return value.map((x)=>from_candid_Property_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlaggedContent>): Array<FlaggedContent> {
    return value.map((x)=>from_candid_FlaggedContent_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Location>): Array<Location> {
    return value.map((x)=>from_candid_Location_n32(_uploadFile, _downloadFile, x));
}
function to_candid_BlogCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory): _BlogCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ContentType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBlogPostInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBlogPostInput): _CreateBlogPostInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_CreateFlagInput_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFlagInput): _CreateFlagInput {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_CreateInquiryInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInquiryInput): _CreateInquiryInput {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_CreateLocationInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLocationInput): _CreateLocationInput {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_CreatePropertyInput_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePropertyInput): _CreatePropertyInput {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_FlagAction_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlagAction): _FlagAction {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryStatus_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_LocationType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationType): _LocationType {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterUserInput_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterUserInput): _RegisterUserInput {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_SearchFilters_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilters): _SearchFilters {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateBlogPostInput_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateBlogPostInput): _UpdateBlogPostInput {
    return to_candid_record_n79(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateLocationInput_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateLocationInput): _UpdateLocationInput {
    return to_candid_record_n83(_uploadFile, _downloadFile, value);
}
function to_candid_UpdatePropertyInput_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePropertyInput): _UpdatePropertyInput {
    return to_candid_record_n85(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUserInput_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUserInput): _UpdateUserInput {
    return to_candid_record_n87(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory | null): [] | [_BlogCategory] {
    return value === null ? candid_none() : candid_some(to_candid_BlogCategory_n12(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    tags: Array<string>;
    featuredImageUrl: string;
    excerpt: string;
    category: BlogCategory;
}): {
    metaDescription: string;
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    tags: Array<string>;
    featuredImageUrl: string;
    excerpt: string;
    category: _BlogCategory;
} {
    return {
        metaDescription: value.metaDescription,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        slug: value.slug,
        tags: value.tags,
        featuredImageUrl: value.featuredImageUrl,
        excerpt: value.excerpt,
        category: to_candid_BlogCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inquiryType: InquiryType;
    propertyId: PropertyId;
    message: string;
    preferredTime?: string;
    contactDetails: string;
}): {
    inquiryType: _InquiryType;
    propertyId: _PropertyId;
    message: string;
    preferredTime: [] | [string];
    contactDetails: string;
} {
    return {
        inquiryType: to_candid_InquiryType_n20(_uploadFile, _downloadFile, value.inquiryType),
        propertyId: value.propertyId,
        message: value.message,
        preferredTime: value.preferredTime ? candid_some(value.preferredTime) : candid_none(),
        contactDetails: value.contactDetails
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    name: string;
    slug: string;
    description: string;
    featuredImageUrl: string;
    longitude: number;
    parentId?: LocationId;
    locationType: LocationType;
}): {
    latitude: number;
    name: string;
    slug: string;
    description: string;
    featuredImageUrl: string;
    longitude: number;
    parentId: [] | [_LocationId];
    locationType: _LocationType;
} {
    return {
        latitude: value.latitude,
        name: value.name,
        slug: value.slug,
        description: value.description,
        featuredImageUrl: value.featuredImageUrl,
        longitude: value.longitude,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none(),
        locationType: to_candid_LocationType_n30(_uploadFile, _downloadFile, value.locationType)
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    title: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    city: string;
    neighborhood: string;
    sqft: bigint;
    description: string;
    amenities: Array<string>;
    longitude: number;
    address: string;
    bathrooms: bigint;
    price: bigint;
    photos: Array<string>;
}): {
    latitude: number;
    title: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    city: string;
    neighborhood: string;
    sqft: bigint;
    description: string;
    amenities: Array<string>;
    longitude: number;
    address: string;
    bathrooms: bigint;
    price: bigint;
    photos: Array<string>;
} {
    return {
        latitude: value.latitude,
        title: value.title,
        propertyType: to_candid_PropertyType_n39(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        city: value.city,
        neighborhood: value.neighborhood,
        sqft: value.sqft,
        description: value.description,
        amenities: value.amenities,
        longitude: value.longitude,
        address: value.address,
        bathrooms: value.bathrooms,
        price: value.price,
        photos: value.photos
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentId: bigint;
    contentType: ContentType;
    reason: string;
}): {
    contentId: bigint;
    contentType: _ContentType;
    reason: string;
} {
    return {
        contentId: value.contentId,
        contentType: to_candid_ContentType_n43(_uploadFile, _downloadFile, value.contentType),
        reason: value.reason
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
    avatarUrl: string;
    phone: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
    avatarUrl: string;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n71(_uploadFile, _downloadFile, value.role),
        email: value.email,
        avatarUrl: value.avatarUrl,
        phone: value.phone
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType?: PropertyType;
    city?: string;
    neighborhood?: string;
    page: bigint;
    pageSize: bigint;
    amenities?: Array<string>;
    minBedrooms?: bigint;
    maxPrice?: bigint;
    maxBedrooms?: bigint;
    keyword?: string;
    minPrice?: bigint;
    minBathrooms?: bigint;
}): {
    propertyType: [] | [_PropertyType];
    city: [] | [string];
    neighborhood: [] | [string];
    page: bigint;
    pageSize: bigint;
    amenities: [] | [Array<string>];
    minBedrooms: [] | [bigint];
    maxPrice: [] | [bigint];
    maxBedrooms: [] | [bigint];
    keyword: [] | [string];
    minPrice: [] | [bigint];
    minBathrooms: [] | [bigint];
} {
    return {
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n39(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        neighborhood: value.neighborhood ? candid_some(value.neighborhood) : candid_none(),
        page: value.page,
        pageSize: value.pageSize,
        amenities: value.amenities ? candid_some(value.amenities) : candid_none(),
        minBedrooms: value.minBedrooms ? candid_some(value.minBedrooms) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        maxBedrooms: value.maxBedrooms ? candid_some(value.maxBedrooms) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        minBathrooms: value.minBathrooms ? candid_some(value.minBathrooms) : candid_none()
    };
}
function to_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metaDescription?: string;
    title?: string;
    content?: string;
    isPublished?: boolean;
    slug?: string;
    tags?: Array<string>;
    featuredImageUrl?: string;
    excerpt?: string;
    category?: BlogCategory;
}): {
    metaDescription: [] | [string];
    title: [] | [string];
    content: [] | [string];
    isPublished: [] | [boolean];
    slug: [] | [string];
    tags: [] | [Array<string>];
    featuredImageUrl: [] | [string];
    excerpt: [] | [string];
    category: [] | [_BlogCategory];
} {
    return {
        metaDescription: value.metaDescription ? candid_some(value.metaDescription) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        content: value.content ? candid_some(value.content) : candid_none(),
        isPublished: value.isPublished ? candid_some(value.isPublished) : candid_none(),
        slug: value.slug ? candid_some(value.slug) : candid_none(),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        featuredImageUrl: value.featuredImageUrl ? candid_some(value.featuredImageUrl) : candid_none(),
        excerpt: value.excerpt ? candid_some(value.excerpt) : candid_none(),
        category: value.category ? candid_some(to_candid_BlogCategory_n12(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    name?: string;
    slug?: string;
    description?: string;
    featuredImageUrl?: string;
    longitude?: number;
}): {
    latitude: [] | [number];
    name: [] | [string];
    slug: [] | [string];
    description: [] | [string];
    featuredImageUrl: [] | [string];
    longitude: [] | [number];
} {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        slug: value.slug ? candid_some(value.slug) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        featuredImageUrl: value.featuredImageUrl ? candid_some(value.featuredImageUrl) : candid_none(),
        longitude: value.longitude ? candid_some(value.longitude) : candid_none()
    };
}
function to_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    title?: string;
    propertyType?: PropertyType;
    bedrooms?: bigint;
    city?: string;
    neighborhood?: string;
    sqft?: bigint;
    description?: string;
    amenities?: Array<string>;
    longitude?: number;
    address?: string;
    bathrooms?: bigint;
    price?: bigint;
    photos?: Array<string>;
}): {
    latitude: [] | [number];
    title: [] | [string];
    propertyType: [] | [_PropertyType];
    bedrooms: [] | [bigint];
    city: [] | [string];
    neighborhood: [] | [string];
    sqft: [] | [bigint];
    description: [] | [string];
    amenities: [] | [Array<string>];
    longitude: [] | [number];
    address: [] | [string];
    bathrooms: [] | [bigint];
    price: [] | [bigint];
    photos: [] | [Array<string>];
} {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n39(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        bedrooms: value.bedrooms ? candid_some(value.bedrooms) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        neighborhood: value.neighborhood ? candid_some(value.neighborhood) : candid_none(),
        sqft: value.sqft ? candid_some(value.sqft) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        amenities: value.amenities ? candid_some(value.amenities) : candid_none(),
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        bathrooms: value.bathrooms ? candid_some(value.bathrooms) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none(),
        photos: value.photos ? candid_some(value.photos) : candid_none()
    };
}
function to_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    email?: string;
    avatarUrl?: string;
    phone?: string;
}): {
    name: [] | [string];
    email: [] | [string];
    avatarUrl: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory): {
    news: null;
} | {
    marketTrends: null;
} | {
    buyingGuide: null;
} | {
    rentalGuide: null;
} {
    return value == BlogCategory.news ? {
        news: null
    } : value == BlogCategory.marketTrends ? {
        marketTrends: null
    } : value == BlogCategory.buyingGuide ? {
        buyingGuide: null
    } : value == BlogCategory.rentalGuide ? {
        rentalGuide: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    requestCallback: null;
} | {
    scheduleVisit: null;
} | {
    contactAgent: null;
} {
    return value == InquiryType.requestCallback ? {
        requestCallback: null
    } : value == InquiryType.scheduleVisit ? {
        scheduleVisit: null
    } : value == InquiryType.contactAgent ? {
        contactAgent: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationType): {
    city: null;
} | {
    neighborhood: null;
} {
    return value == LocationType.city ? {
        city: null
    } : value == LocationType.neighborhood ? {
        neighborhood: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    studio: null;
} | {
    commercial: null;
} | {
    house: null;
} | {
    villa: null;
} | {
    apartment: null;
} {
    return value == PropertyType.studio ? {
        studio: null
    } : value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.house ? {
        house: null
    } : value == PropertyType.villa ? {
        villa: null
    } : value == PropertyType.apartment ? {
        apartment: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    blogPost: null;
} | {
    property: null;
} {
    return value == ContentType.blogPost ? {
        blogPost: null
    } : value == ContentType.property ? {
        property: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    agent: null;
} | {
    buyer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.agent ? {
        agent: null
    } : value == UserRole.buyer ? {
        buyer: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlagAction): {
    remove: null;
} | {
    dismiss: null;
} {
    return value == FlagAction.remove ? {
        remove: null
    } : value == FlagAction.dismiss ? {
        dismiss: null
    } : value;
}
function to_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    closed: null;
} | {
    responded: null;
} | {
    pending: null;
} {
    return value == InquiryStatus.closed ? {
        closed: null
    } : value == InquiryStatus.responded ? {
        responded: null
    } : value == InquiryStatus.pending ? {
        pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
